import java.io.*;
import java.util.Scanner;
class classroom
{
    public static void main(String args[])
    {
        System.out.println("condition");
        System.out.println("enter= \n out =o");
        for(int run=0;run<=100;run++){
            int condition;
            int in_stu;
            int out_stu;
            System.out.println("enter condition");
            Scanner obj = new Scanner(System.in);
            condition=obj.nextInt();
            if(condition==1)
            {
                System.out.println("enter studet");
                Scanner o=new Scanner(System.in);
                in_stu=o.nextInt();


                switch(in_stu){
                    case 1:System.out.println("class in 1 student vaccancy is a 59");
                        break;
                    case 2:System.out.println("class in 2 student vaccancy is a 58");
                        break;
                    case 3:System.out.println("class in 3 student vaccancy is a 57");
                        break; case 4:System.out.println("class in 4 student vaccancy is a 56");
                        break;
                    case 5:System.out.println("class in 5 student vaccancy is a 55");
                        break;
                    case 6:System.out.println("class in 6 student vaccancy is a 54");
                        break;
                    case 7:System.out.println("class in 7 student vaccancy is a 53");
                        break;
                    case 8:System.out.println("class in 8 student vaccancy is a 52");
                        break;
                    case 9:System.out.println("class in 9 student vaccancy is a 51");
                        break;
                    case 10:System.out.println("class in 10 student vaccancy is a 50");
                        break;
                    case 11:System.out.println("class in 11 student vaccancy is a 49");
                        break;
                    case 12:System.out.println("class in 12 student vaccancy is a 48");
                        break;
                    case 13:System.out.println("class in 13 student vaccancy is a 47");
                        break;
                    case 14:System.out.println("class in 14 student vaccancy is a 46");
                        break;
                    case 15:System.out.println("class in 15 student vaccancy is a 45");
                        break;
                    case 16:System.out.println("class in 16 student vaccancy is a 44");
                        break;
                    case 17:System.out.println("class in 17 student vaccancy is a 43");
                        break;
                    case 18:System.out.println("class in 18 student vaccancy is a 42");
                        break;
                    case 19:System.out.println("class in 19 student vaccancy is a 41");
                        break;
                    case 20:System.out.println("class in 20 student vaccancy is a 40");
                        break;
                    case 21:System.out.println("class in 21 student vaccancy is a 39");
                        break;
                    case 22:System.out.println("class in 22 student vaccancy is a 38");
                        break;
                    case 23:System.out.println("class in 23 student vaccancy is a 37");
                        break;
                    case 24:System.out.println("class in 24 student vaccancy is a 36");
                        break;
                    case 25:System.out.println("class in 25 student vaccancy is a 35");
                        break;
                    case 26:System.out.println("class in 26 student vaccancy is a 34");
                        break;
                    case 27:System.out.println("class in 27 student vaccancy is a 33");
                        break;
                    case 28:System.out.println("class in 28 student vaccancy is a 32");
                        break;
                    case 29:System.out.println("class in 29 student vaccancy is a 31");
                        break;
                    case 30 :System.out.println("class in 30 student vaccancy is a 30");
                        break;
                    case 31:System.out.println("class in 31 student vaccancy is a 29");
                        break;
                    case 32:System.out.println("class in 32 student vaccancy is a 28");
                        break;
                    case 33:System.out.println("class in 33 student vaccancy is a 27");
                        break;
                    case  34:System.out.println("class in 34 student vaccancy is a 26");
                        break;
                    case 35:System.out.println("class in 35 student vaccancy is a 25");
                        break;
                    case 36:System.out.println("class in 36 student vaccancy is a 24");
                        break;
                    case 37:System.out.println("class in 37 student vaccancy is a 23");
                        break;
                    case 38:System.out.println("class in 38 student vaccancy is a 22");
                        break;
                    case 39:System.out.println("class in 39 student vaccancy is a 44");
                        break;
                    case 40:System.out.println("class in 40 student vaccancy is a 20");
                        break;
                    case 41:System.out.println("class in 41 student vaccancy is a 19");
                        break;
                    case 42:System.out.println("class in 42 student vaccancy is a 18");
                        break;
                    case 43:System.out.println("class in 43 student vaccancy is a 17");
                        break;
                    case 44:System.out.println("class in 44 student vaccancy is a 16");
                        break;
                    case 45:System.out.println("class in 45 student vaccancy is a 15");
                        break;
                    case 46:System.out.println("class in 46 student vaccancy is a 14");
                        break;
                    case 47:System.out.println("class in 47 student vaccancy is a 13");
                        break;
                    case 48:System.out.println("class in 48 student vaccancy is a 12");
                        break;
                    case 49:System.out.println("class in 49 student vaccancy is a 11");
                        break;
                    case 50:System.out.println("class in 50 student vaccancy is a 10");
                        break;
                    case 51:System.out.println("class in 51 student vaccancy is a 9");
                        break;
                    case 52 :System.out.println("class in 52 student vaccancy is a 8");
                        break;
                    case 53:System.out.println("class in 53 student vaccancy is a 7");
                        break;
                    case 54:System.out.println("class in 54 student vaccancy is a 6");
                        break;
                    case 55:System.out.println("class in 55 student vaccancy is a 5");
                        break;
                    case  56:System.out.println("class in 56 student vaccancy is a 4");
                        break;
                    case 57:System.out.println("class in 57 student vaccancy is a 3");
                        break;
                    case 58:System.out.println("class in 58 student vaccancy is a 2");
                        break;
                    case 59:System.out.println("class in 59 student vaccancy is a 1");
                        break;
                    case 60:System.out.println("class full");
                        break;
                    default:System.out.println("class empty");
                }
            }
else
            {
                System.out.println("out studet");
                Scanner o=new Scanner(System.in);
                out_stu=o.nextInt();

                switch(out_stu){
                    case 1:System.out.println("class in 1 student vaccancy is a 1");
                        break;
                    case 2:System.out.println("class in 2 student vaccancy is a 2");
                        break;
                    case 3:System.out.println("class in 3 student vaccancy is a 3");
                        break;
                    case 4:System.out.println("class in 4 student vaccancy is a 4");
                        break;
                    case 5:System.out.println("class in 5 student vaccancy is a 5");
                        break;
                    case 6:System.out.println("class in 6 student vaccancy is a 6");
                        break;
                    case 7:System.out.println("class in 7 student vaccancy is a 7");
                        break;
                    case 8:System.out.println("class in 8 student vaccancy is a 8");
                        break;
                    case 9:System.out.println("class in 9 student vaccancy is a 9");
                        break;
                    case 10:System.out.println("class in 10 student vaccancy is a 10");
                        break;
                    case 11:System.out.println("class in 11 student vaccancy is a 11");
                        break;
                    case 12:System.out.println("class in 12 student vaccancy is a 12");
                        break;
                    case 13:System.out.println("class in 13 student vaccancy is a 13");
                        break;
                    case 14:System.out.println("class in 14 student vaccancy is a 14");
                        break;
                    case 15:System.out.println("class in 15 student vaccancy is a 15");
                        break;
                    case 16:System.out.println("class in 16 student vaccancy is a 16");
                        break;
                    case 17:System.out.println("class in 17 student vaccancy is a 17");
                        break;
                    case 18:System.out.println("class in 18 student vaccancy is a 18");
                        break;
                    case 19:System.out.println("class in 42 student vaccancy is a 19");
                        break;
                    case 20:System.out.println("class in 41 student vaccancy is a 20");
                        break;
                    case 21:System.out.println("class in 40 student vaccancy is a 21");
                        break;
                    case 22:System.out.println("class in 39 student vaccancy is a 22");
                        break;
                    case 23:System.out.println("class in 37 student vaccancy is a 23");
                        break;
                    case 24:System.out.println("class in 36 student vaccancy is a 24");
                        break;
                    case 25:System.out.println("class in 35 student vaccancy is a 25");
                        break;
                    case 26:System.out.println("class in 34 student vaccancy is a 26");
                        break;
                    case 27:System.out.println("class in 33 student vaccancy is a 27");
                        break;
                    case 28:System.out.println("class in 32 student vaccancy is a 28");
                        break;
                    case 29:System.out.println("class in 31 student vaccancy is a 29");
                        break;
                    case 30 :System.out.println("class in 30 student vaccancy is a 30");
                        break;
                    case 31:System.out.println("class in 29 student vaccancy is a 31");
                        break;
                    case 32:System.out.println("class in 28 student vaccancy is a 32");
                        break;
                    case 33:System.out.println("class in 27 student vaccancy is a 33");
                        break;
                    case  34:System.out.println("class in 26 student vaccancy is a 34");
                        break;
                    case 35:System.out.println("class in 25 student vaccancy is a 35");
                        break;
                    case 36:System.out.println("class in 24 student vaccancy is a 36");
                        break;
                    case 37:System.out.println("class in 23 student vaccancy is a 37");
                        break;
                    case 38:System.out.println("class in 22 student vaccancy is a 38");

                        break;
                    case 39:System.out.println("class in 21 student vaccancy is a 39");
                        break;
                    case 40:System.out.println("class in 20 student vaccancy is a 40");
                        break;
                    case 41:System.out.println("class in 19 student vaccancy is a 41");
                        break;
                    case 42:System.out.println("class in 18 student vaccancy is a 42");
                        break;
                    case 43:System.out.println("class in 17 student vaccancy is a 43");
                        break;
                    case 44:System.out.println("class in 16 student vaccancy is a 44");
                        break;
                    case 45:System.out.println("class in 15 student vaccancy is a 45");
                        break;
                    case 46:System.out.println("class in 14  student vaccancy is a 46");
                        break;
                    case 47:System.out.println("class in 13 student vaccancy is a 47");
                        break;
                    case 48:System.out.println("class in 12 student vaccancy is a 48");
                        break;
                    case 49:System.out.println("class in 11 student vaccancy is a 49");
                        break;
                    case 50:System.out.println("class in 10 student vaccancy is a 50");
                        break;
                    case 51:System.out.println("class in 9 student vaccancy is a 51");
                        break;
                    case 52:System.out.println("class in 8 student vaccancy is a 52");
                        break;
                    case 53 :System.out.println("class in 7 student vaccancy is a 53");
                        break;
                    case 54:System.out.println("class in 6 student vaccancy is a 54");
                        break;
                    case 55:System.out.println("class in 5 student vaccancy is a 55");
                        break;
                    case 56:System.out.println("class in 4 student vaccancy is a 56");
                        break;
                    case  57:System.out.println("class in 3 student vaccancy is a 57");
                        break;
                    case 58:System.out.println("class in 2 student vaccancy is a 58");
                        break;
                    case 59:System.out.println("class in 1 student vaccancy is a 59");
                        break;
                    case 60 :System.out.println("class empty");
                        break;
                    default:System.out.println("class full");
                }

            }

        }

    }
}